"""Pydantic schemas for request/response validation"""
from app.schemas.user import UserCreate, UserLogin, UserResponse, Token
from app.schemas.expert_application import (
    ExpertApplicationCreate,
    ExpertApplicationSubmit,
    ExpertApplicationUpdate,
    ExpertApplicationResponse,
    ExpertApplicationStatusResponse,
    ExpertApplicationListResponse,
)
from app.schemas.battle import (
    BattlePromptCreate,
    BattlePromptUpdate,
    BattlePromptResponse,
    BattlePromptListResponse,
    BattleEntryCreate,
    BattleEntryUpdate,
    BattleEntryResponse,
    BattleVoteCreate,
    BattleVoteResponse,
    BattleVoteStats,
    BattleChallengeCreate,
    BattleChallengeResponse,
    BattleCreate,
    BattleJoinQueue,
    BattleResponse,
    BattleListResponse,
    QueueStatus,
    BattleStats,
    BattleLeaderboardEntry,
    BattleLeaderboardResponse,
    BattleResults,
    BattleFilters,
)

__all__ = [
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "Token",
    "ExpertApplicationCreate",
    "ExpertApplicationSubmit",
    "ExpertApplicationUpdate",
    "ExpertApplicationResponse",
    "ExpertApplicationStatusResponse",
    "ExpertApplicationListResponse",
    # Battle schemas
    "BattlePromptCreate",
    "BattlePromptUpdate",
    "BattlePromptResponse",
    "BattlePromptListResponse",
    "BattleEntryCreate",
    "BattleEntryUpdate",
    "BattleEntryResponse",
    "BattleVoteCreate",
    "BattleVoteResponse",
    "BattleVoteStats",
    "BattleChallengeCreate",
    "BattleChallengeResponse",
    "BattleCreate",
    "BattleJoinQueue",
    "BattleResponse",
    "BattleListResponse",
    "QueueStatus",
    "BattleStats",
    "BattleLeaderboardEntry",
    "BattleLeaderboardResponse",
    "BattleResults",
    "BattleFilters",
]
