"""
Badge Definitions for Critvue

This module contains all default badge definitions used by the BadgeService.
Separated from the service logic for better maintainability.

Total: 75 badges across 7 categories:
- SKILL BADGES - Visual Arts (16 badges)
- SKILL BADGES - Video & Streaming (10 badges)
- SKILL BADGES - Writing & Audio (10 badges)
- CREATOR BADGES (10 badges)
- COMMUNITY BADGES (8 badges)
- MILESTONE BADGES (10 badges)
- QUALITY BADGES (8 badges)
- STREAK BADGES (6 badges)
- SPECIAL BADGES (8 badges)
"""

from app.models.badge import BadgeCategory, BadgeRarity


DEFAULT_BADGES = [
    # ============================================
    # SKILL BADGES - Visual Arts (16 badges)
    # ============================================

    # Photography
    {
        "code": "skill_photography_apprentice",
        "name": "Photography Apprentice",
        "description": "Completed 5 photography reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 10,
        "xp_reward": 10,
        "requirement_type": "content_type_reviews",
        "requirement_value": 5,
        "requirement_skill": "photography",
    },
    {
        "code": "skill_photography_expert",
        "name": "Photography Expert",
        "description": "Completed 25 photography reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 50,
        "xp_reward": 50,
        "requirement_type": "content_type_reviews",
        "requirement_value": 25,
        "requirement_skill": "photography",
    },

    # Digital Art
    {
        "code": "skill_digital_art_apprentice",
        "name": "Digital Art Apprentice",
        "description": "Completed 5 digital art reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 10,
        "xp_reward": 10,
        "requirement_type": "content_type_reviews",
        "requirement_value": 5,
        "requirement_skill": "digital_art",
    },
    {
        "code": "skill_digital_art_expert",
        "name": "Digital Art Expert",
        "description": "Completed 25 digital art reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 50,
        "xp_reward": 50,
        "requirement_type": "content_type_reviews",
        "requirement_value": 25,
        "requirement_skill": "digital_art",
    },

    # Illustration
    {
        "code": "skill_illustration_apprentice",
        "name": "Illustration Apprentice",
        "description": "Completed 5 illustration reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 10,
        "xp_reward": 10,
        "requirement_type": "content_type_reviews",
        "requirement_value": 5,
        "requirement_skill": "illustration",
    },
    {
        "code": "skill_illustration_expert",
        "name": "Illustration Expert",
        "description": "Completed 25 illustration reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 50,
        "xp_reward": 50,
        "requirement_type": "content_type_reviews",
        "requirement_value": 25,
        "requirement_skill": "illustration",
    },

    # Graphic Design
    {
        "code": "skill_graphic_design_apprentice",
        "name": "Graphic Design Apprentice",
        "description": "Completed 5 graphic design reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 10,
        "xp_reward": 10,
        "requirement_type": "content_type_reviews",
        "requirement_value": 5,
        "requirement_skill": "graphic_design",
    },
    {
        "code": "skill_graphic_design_expert",
        "name": "Graphic Design Expert",
        "description": "Completed 25 graphic design reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 50,
        "xp_reward": 50,
        "requirement_type": "content_type_reviews",
        "requirement_value": 25,
        "requirement_skill": "graphic_design",
    },

    # Character Design
    {
        "code": "skill_character_design_apprentice",
        "name": "Character Design Apprentice",
        "description": "Completed 5 character design reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 10,
        "xp_reward": 10,
        "requirement_type": "content_type_reviews",
        "requirement_value": 5,
        "requirement_skill": "character_design",
    },
    {
        "code": "skill_character_design_expert",
        "name": "Character Design Expert",
        "description": "Completed 25 character design reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 50,
        "xp_reward": 50,
        "requirement_type": "content_type_reviews",
        "requirement_value": 25,
        "requirement_skill": "character_design",
    },

    # Concept Art
    {
        "code": "skill_concept_art_apprentice",
        "name": "Concept Art Apprentice",
        "description": "Completed 5 concept art reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 10,
        "xp_reward": 10,
        "requirement_type": "content_type_reviews",
        "requirement_value": 5,
        "requirement_skill": "concept_art",
    },
    {
        "code": "skill_concept_art_expert",
        "name": "Concept Art Expert",
        "description": "Completed 25 concept art reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 50,
        "xp_reward": 50,
        "requirement_type": "content_type_reviews",
        "requirement_value": 25,
        "requirement_skill": "concept_art",
    },

    # Traditional Art
    {
        "code": "skill_traditional_art_apprentice",
        "name": "Traditional Art Apprentice",
        "description": "Completed 5 traditional art reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 10,
        "xp_reward": 10,
        "requirement_type": "content_type_reviews",
        "requirement_value": 5,
        "requirement_skill": "traditional_art",
    },
    {
        "code": "skill_traditional_art_expert",
        "name": "Traditional Art Expert",
        "description": "Completed 25 traditional art reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 50,
        "xp_reward": 50,
        "requirement_type": "content_type_reviews",
        "requirement_value": 25,
        "requirement_skill": "traditional_art",
    },

    # ============================================
    # SKILL BADGES - Video & Streaming (10 badges)
    # ============================================

    # Video Editing
    {
        "code": "skill_video_editing_apprentice",
        "name": "Video Editing Apprentice",
        "description": "Completed 5 video editing reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 10,
        "xp_reward": 10,
        "requirement_type": "content_type_reviews",
        "requirement_value": 5,
        "requirement_skill": "video_editing",
    },
    {
        "code": "skill_video_editing_expert",
        "name": "Video Editing Expert",
        "description": "Completed 25 video editing reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 50,
        "xp_reward": 50,
        "requirement_type": "content_type_reviews",
        "requirement_value": 25,
        "requirement_skill": "video_editing",
    },

    # YouTube Content
    {
        "code": "skill_youtube_apprentice",
        "name": "YouTube Apprentice",
        "description": "Completed 5 YouTube content reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 10,
        "xp_reward": 10,
        "requirement_type": "content_type_reviews",
        "requirement_value": 5,
        "requirement_skill": "youtube",
    },
    {
        "code": "skill_youtube_expert",
        "name": "YouTube Expert",
        "description": "Completed 25 YouTube content reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 50,
        "xp_reward": 50,
        "requirement_type": "content_type_reviews",
        "requirement_value": 25,
        "requirement_skill": "youtube",
    },

    # TikTok/Reels
    {
        "code": "skill_short_form_apprentice",
        "name": "Short-Form Apprentice",
        "description": "Completed 5 TikTok/Reels/Shorts reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 10,
        "xp_reward": 10,
        "requirement_type": "content_type_reviews",
        "requirement_value": 5,
        "requirement_skill": "short_form",
    },
    {
        "code": "skill_short_form_expert",
        "name": "Short-Form Expert",
        "description": "Completed 25 TikTok/Reels/Shorts reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 50,
        "xp_reward": 50,
        "requirement_type": "content_type_reviews",
        "requirement_value": 25,
        "requirement_skill": "short_form",
    },

    # Streaming/Live
    {
        "code": "skill_streaming_apprentice",
        "name": "Streaming Apprentice",
        "description": "Completed 5 stream/live content reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 10,
        "xp_reward": 10,
        "requirement_type": "content_type_reviews",
        "requirement_value": 5,
        "requirement_skill": "streaming",
    },
    {
        "code": "skill_streaming_expert",
        "name": "Streaming Expert",
        "description": "Completed 25 stream/live content reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 50,
        "xp_reward": 50,
        "requirement_type": "content_type_reviews",
        "requirement_value": 25,
        "requirement_skill": "streaming",
    },

    # Animation/Motion
    {
        "code": "skill_animation_apprentice",
        "name": "Animation Apprentice",
        "description": "Completed 5 animation/motion reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 10,
        "xp_reward": 10,
        "requirement_type": "content_type_reviews",
        "requirement_value": 5,
        "requirement_skill": "animation",
    },
    {
        "code": "skill_animation_expert",
        "name": "Animation Expert",
        "description": "Completed 25 animation/motion reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 50,
        "xp_reward": 50,
        "requirement_type": "content_type_reviews",
        "requirement_value": 25,
        "requirement_skill": "animation",
    },

    # ============================================
    # SKILL BADGES - Writing & Audio (10 badges)
    # ============================================

    # Creative Writing
    {
        "code": "skill_creative_writing_apprentice",
        "name": "Creative Writing Apprentice",
        "description": "Completed 5 creative writing reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 10,
        "xp_reward": 10,
        "requirement_type": "content_type_reviews",
        "requirement_value": 5,
        "requirement_skill": "creative_writing",
    },
    {
        "code": "skill_creative_writing_expert",
        "name": "Creative Writing Expert",
        "description": "Completed 25 creative writing reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 50,
        "xp_reward": 50,
        "requirement_type": "content_type_reviews",
        "requirement_value": 25,
        "requirement_skill": "creative_writing",
    },

    # Copywriting
    {
        "code": "skill_copywriting_apprentice",
        "name": "Copywriting Apprentice",
        "description": "Completed 5 copywriting reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 10,
        "xp_reward": 10,
        "requirement_type": "content_type_reviews",
        "requirement_value": 5,
        "requirement_skill": "copywriting",
    },
    {
        "code": "skill_copywriting_expert",
        "name": "Copywriting Expert",
        "description": "Completed 25 copywriting reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 50,
        "xp_reward": 50,
        "requirement_type": "content_type_reviews",
        "requirement_value": 25,
        "requirement_skill": "copywriting",
    },

    # Poetry
    {
        "code": "skill_poetry_apprentice",
        "name": "Poetry Apprentice",
        "description": "Completed 5 poetry reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 10,
        "xp_reward": 10,
        "requirement_type": "content_type_reviews",
        "requirement_value": 5,
        "requirement_skill": "poetry",
    },
    {
        "code": "skill_poetry_expert",
        "name": "Poetry Expert",
        "description": "Completed 25 poetry reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 50,
        "xp_reward": 50,
        "requirement_type": "content_type_reviews",
        "requirement_value": 25,
        "requirement_skill": "poetry",
    },

    # Music Production
    {
        "code": "skill_music_production_apprentice",
        "name": "Music Production Apprentice",
        "description": "Completed 5 music production reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 10,
        "xp_reward": 10,
        "requirement_type": "content_type_reviews",
        "requirement_value": 5,
        "requirement_skill": "music_production",
    },
    {
        "code": "skill_music_production_expert",
        "name": "Music Production Expert",
        "description": "Completed 25 music production reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 50,
        "xp_reward": 50,
        "requirement_type": "content_type_reviews",
        "requirement_value": 25,
        "requirement_skill": "music_production",
    },

    # Podcasting
    {
        "code": "skill_podcasting_apprentice",
        "name": "Podcasting Apprentice",
        "description": "Completed 5 podcast reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 10,
        "xp_reward": 10,
        "requirement_type": "content_type_reviews",
        "requirement_value": 5,
        "requirement_skill": "podcasting",
    },
    {
        "code": "skill_podcasting_expert",
        "name": "Podcasting Expert",
        "description": "Completed 25 podcast reviews",
        "category": BadgeCategory.SKILL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 50,
        "xp_reward": 50,
        "requirement_type": "content_type_reviews",
        "requirement_value": 25,
        "requirement_skill": "podcasting",
    },

    # ============================================
    # CREATOR BADGES (10 badges)
    # ============================================

    {
        "code": "creator_first_request",
        "name": "First Request",
        "description": "Submitted your first review request",
        "category": BadgeCategory.MILESTONE,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 5,
        "xp_reward": 5,
        "requirement_type": "total_requests",
        "requirement_value": 1,
    },
    {
        "code": "creator_feedback_seeker",
        "name": "Feedback Seeker",
        "description": "Received 5 completed reviews on your work",
        "category": BadgeCategory.MILESTONE,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 15,
        "xp_reward": 15,
        "requirement_type": "reviews_received",
        "requirement_value": 5,
    },
    {
        "code": "creator_improvement_driven",
        "name": "Improvement Driven",
        "description": "Received 25 completed reviews on your work",
        "category": BadgeCategory.MILESTONE,
        "rarity": BadgeRarity.UNCOMMON,
        "karma_reward": 30,
        "xp_reward": 30,
        "requirement_type": "reviews_received",
        "requirement_value": 25,
    },
    {
        "code": "creator_quality_patron",
        "name": "Quality Patron",
        "description": "Paid for 5 expert reviews",
        "category": BadgeCategory.MILESTONE,
        "rarity": BadgeRarity.UNCOMMON,
        "karma_reward": 40,
        "xp_reward": 40,
        "requirement_type": "expert_reviews_paid",
        "requirement_value": 5,
    },
    {
        "code": "creator_generous_rater",
        "name": "Generous Rater",
        "description": "Gave 10 five-star helpful ratings to reviewers",
        "category": BadgeCategory.QUALITY,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 20,
        "xp_reward": 20,
        "requirement_type": "five_star_ratings_given",
        "requirement_value": 10,
    },
    {
        "code": "creator_detailed_requester",
        "name": "Detailed Requester",
        "description": "Submitted 5 requests with all fields completed",
        "category": BadgeCategory.QUALITY,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 15,
        "xp_reward": 15,
        "requirement_type": "detailed_requests",
        "requirement_value": 5,
    },
    {
        "code": "creator_quick_responder",
        "name": "Quick Responder",
        "description": "Accepted/rated 10 reviews within 24 hours",
        "category": BadgeCategory.QUALITY,
        "rarity": BadgeRarity.UNCOMMON,
        "karma_reward": 25,
        "xp_reward": 25,
        "requirement_type": "quick_responses",
        "requirement_value": 10,
    },
    {
        "code": "creator_revision_master",
        "name": "Revision Master",
        "description": "Successfully requested and received 3 review revisions",
        "category": BadgeCategory.QUALITY,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 35,
        "xp_reward": 35,
        "requirement_type": "revisions_received",
        "requirement_value": 3,
    },
    {
        "code": "creator_portfolio_builder",
        "name": "Portfolio Builder",
        "description": "Added 5 items to your portfolio",
        "category": BadgeCategory.MILESTONE,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 20,
        "xp_reward": 20,
        "requirement_type": "portfolio_items",
        "requirement_value": 5,
    },
    {
        "code": "creator_critvue_champion",
        "name": "Critvue Champion",
        "description": "Received 100+ reviews with 4.5+ average rating given",
        "category": BadgeCategory.SPECIAL,
        "rarity": BadgeRarity.EPIC,
        "karma_reward": 150,
        "xp_reward": 150,
        "requirement_type": "champion_creator",
        "requirement_value": 100,
    },

    # ============================================
    # COMMUNITY BADGES (8 badges)
    # ============================================

    {
        "code": "community_profile_complete",
        "name": "Profile Complete",
        "description": "Filled out all profile fields including avatar",
        "category": BadgeCategory.MILESTONE,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 10,
        "xp_reward": 10,
        "requirement_type": "profile_complete",
        "requirement_value": 1,
    },
    {
        "code": "community_first_referral",
        "name": "First Referral",
        "description": "Referred a user who completed their first review",
        "category": BadgeCategory.SPECIAL,
        "rarity": BadgeRarity.UNCOMMON,
        "karma_reward": 30,
        "xp_reward": 30,
        "requirement_type": "referrals",
        "requirement_value": 1,
    },
    {
        "code": "community_network_builder",
        "name": "Network Builder",
        "description": "Referred 5 active users to the platform",
        "category": BadgeCategory.SPECIAL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 75,
        "xp_reward": 75,
        "requirement_type": "referrals",
        "requirement_value": 5,
    },
    {
        "code": "community_helpful_mentor",
        "name": "Helpful Mentor",
        "description": "10 of your reviews were marked as especially educational",
        "category": BadgeCategory.QUALITY,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 60,
        "xp_reward": 60,
        "requirement_type": "educational_reviews",
        "requirement_value": 10,
    },
    {
        "code": "community_constructive_voice",
        "name": "Constructive Voice",
        "description": "Zero disputes lost in 50+ reviews",
        "category": BadgeCategory.QUALITY,
        "rarity": BadgeRarity.EPIC,
        "karma_reward": 100,
        "xp_reward": 100,
        "requirement_type": "no_disputes_lost",
        "requirement_value": 50,
    },
    {
        "code": "community_pillar",
        "name": "Community Pillar",
        "description": "Active for 6+ months with 100+ reviews",
        "category": BadgeCategory.SPECIAL,
        "rarity": BadgeRarity.EPIC,
        "karma_reward": 150,
        "xp_reward": 150,
        "requirement_type": "community_pillar",
        "requirement_value": 100,
    },
    {
        "code": "community_trending_reviewer",
        "name": "Trending Reviewer",
        "description": "Reached top 10 on the weekly leaderboard",
        "category": BadgeCategory.SEASONAL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 50,
        "xp_reward": 50,
        "requirement_type": "leaderboard_top10",
        "requirement_value": 1,
    },
    {
        "code": "community_weekly_champion",
        "name": "Weekly Champion",
        "description": "First place on the weekly leaderboard",
        "category": BadgeCategory.SEASONAL,
        "rarity": BadgeRarity.LEGENDARY,
        "karma_reward": 200,
        "xp_reward": 200,
        "requirement_type": "leaderboard_first",
        "requirement_value": 1,
    },

    # ============================================
    # MILESTONE BADGES (10 badges)
    # ============================================

    {
        "code": "milestone_first_review",
        "name": "First Steps",
        "description": "Submitted your first review",
        "category": BadgeCategory.MILESTONE,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 5,
        "xp_reward": 5,
        "requirement_type": "total_reviews",
        "requirement_value": 1,
    },
    {
        "code": "milestone_10_reviews",
        "name": "Getting Started",
        "description": "Completed 10 reviews",
        "category": BadgeCategory.MILESTONE,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 15,
        "xp_reward": 15,
        "requirement_type": "total_reviews",
        "requirement_value": 10,
    },
    {
        "code": "milestone_25_reviews",
        "name": "Quarter Century",
        "description": "Completed 25 reviews",
        "category": BadgeCategory.MILESTONE,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 20,
        "xp_reward": 20,
        "requirement_type": "total_reviews",
        "requirement_value": 25,
    },
    {
        "code": "milestone_50_reviews",
        "name": "Dedicated Reviewer",
        "description": "Completed 50 reviews",
        "category": BadgeCategory.MILESTONE,
        "rarity": BadgeRarity.UNCOMMON,
        "karma_reward": 30,
        "xp_reward": 30,
        "requirement_type": "total_reviews",
        "requirement_value": 50,
    },
    {
        "code": "milestone_100_reviews",
        "name": "Century Club",
        "description": "Completed 100 reviews",
        "category": BadgeCategory.MILESTONE,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 75,
        "xp_reward": 75,
        "requirement_type": "total_reviews",
        "requirement_value": 100,
    },
    {
        "code": "milestone_200_reviews",
        "name": "Double Century",
        "description": "Completed 200 reviews",
        "category": BadgeCategory.MILESTONE,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 100,
        "xp_reward": 100,
        "requirement_type": "total_reviews",
        "requirement_value": 200,
    },
    {
        "code": "milestone_500_reviews",
        "name": "Review Legend",
        "description": "Completed 500 reviews",
        "category": BadgeCategory.MILESTONE,
        "rarity": BadgeRarity.EPIC,
        "karma_reward": 200,
        "xp_reward": 200,
        "requirement_type": "total_reviews",
        "requirement_value": 500,
    },
    {
        "code": "milestone_1000_reviews",
        "name": "Thousand Club",
        "description": "Completed 1,000 reviews - true dedication!",
        "category": BadgeCategory.MILESTONE,
        "rarity": BadgeRarity.LEGENDARY,
        "karma_reward": 500,
        "xp_reward": 500,
        "requirement_type": "total_reviews",
        "requirement_value": 1000,
    },
    {
        "code": "milestone_sparks_legend",
        "name": "Sparks Legend",
        "description": "Reached 5,000 Sparks",
        "category": BadgeCategory.MILESTONE,
        "rarity": BadgeRarity.EPIC,
        "karma_reward": 100,
        "xp_reward": 100,
        "requirement_type": "total_sparks",
        "requirement_value": 5000,
    },
    {
        "code": "milestone_xp_master",
        "name": "XP Master",
        "description": "Reached 10,000 XP - permanent progress!",
        "category": BadgeCategory.MILESTONE,
        "rarity": BadgeRarity.LEGENDARY,
        "karma_reward": 150,
        "xp_reward": 150,
        "requirement_type": "total_xp",
        "requirement_value": 10000,
    },

    # ============================================
    # QUALITY BADGES (8 badges)
    # ============================================

    {
        "code": "quality_helpful_10",
        "name": "Helpful Hand",
        "description": "Received 10 five-star helpful ratings",
        "category": BadgeCategory.QUALITY,
        "rarity": BadgeRarity.UNCOMMON,
        "karma_reward": 25,
        "xp_reward": 25,
        "requirement_type": "five_star_ratings",
        "requirement_value": 10,
    },
    {
        "code": "quality_helpful_50",
        "name": "Invaluable Reviewer",
        "description": "Received 50 five-star helpful ratings",
        "category": BadgeCategory.QUALITY,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 75,
        "xp_reward": 75,
        "requirement_type": "five_star_ratings",
        "requirement_value": 50,
    },
    {
        "code": "quality_helpful_100",
        "name": "Five-Star Legend",
        "description": "Received 100 five-star helpful ratings",
        "category": BadgeCategory.QUALITY,
        "rarity": BadgeRarity.EPIC,
        "karma_reward": 150,
        "xp_reward": 150,
        "requirement_type": "five_star_ratings",
        "requirement_value": 100,
    },
    {
        "code": "quality_acceptance_90",
        "name": "Trusted Voice",
        "description": "Maintained 90%+ acceptance rate (min 20 reviews)",
        "category": BadgeCategory.QUALITY,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 50,
        "xp_reward": 50,
        "requirement_type": "acceptance_rate",
        "requirement_value": 90,
    },
    {
        "code": "quality_perfectionist",
        "name": "Perfectionist",
        "description": "Maintained 95%+ acceptance rate (min 50 reviews)",
        "category": BadgeCategory.QUALITY,
        "rarity": BadgeRarity.EPIC,
        "karma_reward": 100,
        "xp_reward": 100,
        "requirement_type": "acceptance_rate_high",
        "requirement_value": 95,
    },
    {
        "code": "quality_zero_rejections",
        "name": "Zero Rejections",
        "description": "25 consecutive accepted reviews without rejection",
        "category": BadgeCategory.QUALITY,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 60,
        "xp_reward": 60,
        "requirement_type": "consecutive_accepted",
        "requirement_value": 25,
    },
    {
        "code": "quality_detail_master",
        "name": "Detail Master",
        "description": "20 reviews praised for thoroughness",
        "category": BadgeCategory.QUALITY,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 50,
        "xp_reward": 50,
        "requirement_type": "thorough_reviews",
        "requirement_value": 20,
    },
    {
        "code": "quality_speed_demon",
        "name": "Speed Demon",
        "description": "Delivered 10 reviews well under the deadline",
        "category": BadgeCategory.QUALITY,
        "rarity": BadgeRarity.UNCOMMON,
        "karma_reward": 30,
        "xp_reward": 30,
        "requirement_type": "fast_deliveries",
        "requirement_value": 10,
    },

    # ============================================
    # STREAK BADGES (6 badges)
    # ============================================

    {
        "code": "streak_7_days",
        "name": "Week Warrior",
        "description": "Maintained a 7-day review streak",
        "category": BadgeCategory.STREAK,
        "rarity": BadgeRarity.COMMON,
        "karma_reward": 15,
        "xp_reward": 15,
        "requirement_type": "streak_days",
        "requirement_value": 7,
    },
    {
        "code": "streak_14_days",
        "name": "Fortnight Fighter",
        "description": "Maintained a 14-day review streak",
        "category": BadgeCategory.STREAK,
        "rarity": BadgeRarity.UNCOMMON,
        "karma_reward": 30,
        "xp_reward": 30,
        "requirement_type": "streak_days",
        "requirement_value": 14,
    },
    {
        "code": "streak_30_days",
        "name": "Month Master",
        "description": "Maintained a 30-day review streak",
        "category": BadgeCategory.STREAK,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 100,
        "xp_reward": 100,
        "requirement_type": "streak_days",
        "requirement_value": 30,
    },
    {
        "code": "streak_60_days",
        "name": "60-Day Dynamo",
        "description": "Maintained a 60-day review streak",
        "category": BadgeCategory.STREAK,
        "rarity": BadgeRarity.EPIC,
        "karma_reward": 200,
        "xp_reward": 200,
        "requirement_type": "streak_days",
        "requirement_value": 60,
    },
    {
        "code": "streak_100_days",
        "name": "Unstoppable",
        "description": "Maintained a 100-day review streak",
        "category": BadgeCategory.STREAK,
        "rarity": BadgeRarity.LEGENDARY,
        "karma_reward": 500,
        "xp_reward": 500,
        "requirement_type": "streak_days",
        "requirement_value": 100,
    },
    {
        "code": "streak_weekend_warrior",
        "name": "Weekend Warrior",
        "description": "Completed reviews on 4 consecutive weekends",
        "category": BadgeCategory.STREAK,
        "rarity": BadgeRarity.UNCOMMON,
        "karma_reward": 25,
        "xp_reward": 25,
        "requirement_type": "weekend_streak",
        "requirement_value": 4,
    },

    # ============================================
    # SPECIAL BADGES (8 badges)
    # ============================================

    {
        "code": "special_early_adopter",
        "name": "Early Adopter",
        "description": "Joined during the beta period",
        "category": BadgeCategory.SPECIAL,
        "rarity": BadgeRarity.EPIC,
        "karma_reward": 100,
        "xp_reward": 100,
        "requirement_type": "manual",
        "requirement_value": 0,
    },
    {
        "code": "special_community_helper",
        "name": "Community Helper",
        "description": "Helped improve the platform through feedback",
        "category": BadgeCategory.SPECIAL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 50,
        "xp_reward": 50,
        "requirement_type": "manual",
        "requirement_value": 0,
    },
    {
        "code": "special_bug_hunter",
        "name": "Bug Hunter",
        "description": "Reported a confirmed bug that was fixed",
        "category": BadgeCategory.SPECIAL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 75,
        "xp_reward": 75,
        "requirement_type": "manual",
        "requirement_value": 0,
    },
    {
        "code": "special_feature_pioneer",
        "name": "Feature Pioneer",
        "description": "First to use a new platform feature",
        "category": BadgeCategory.SPECIAL,
        "rarity": BadgeRarity.UNCOMMON,
        "karma_reward": 25,
        "xp_reward": 25,
        "requirement_type": "manual",
        "requirement_value": 0,
    },
    {
        "code": "special_holiday_hero",
        "name": "Holiday Hero",
        "description": "Completed a review on a major holiday",
        "category": BadgeCategory.SEASONAL,
        "rarity": BadgeRarity.UNCOMMON,
        "karma_reward": 30,
        "xp_reward": 30,
        "requirement_type": "holiday_review",
        "requirement_value": 1,
    },
    {
        "code": "special_new_year_reviewer",
        "name": "New Year Reviewer",
        "description": "First review of the calendar year",
        "category": BadgeCategory.SEASONAL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 50,
        "xp_reward": 50,
        "requirement_type": "manual",
        "requirement_value": 0,
    },
    {
        "code": "special_anniversary",
        "name": "Anniversary Badge",
        "description": "Celebrated 1 year on Critvue",
        "category": BadgeCategory.SPECIAL,
        "rarity": BadgeRarity.RARE,
        "karma_reward": 75,
        "xp_reward": 75,
        "requirement_type": "account_age_days",
        "requirement_value": 365,
    },
    {
        "code": "special_og_status",
        "name": "OG Status",
        "description": "2+ years on platform with 500+ reviews",
        "category": BadgeCategory.SPECIAL,
        "rarity": BadgeRarity.LEGENDARY,
        "karma_reward": 300,
        "xp_reward": 300,
        "requirement_type": "og_status",
        "requirement_value": 500,
    },
]
